Add default subcommand to commands
ZakFahey/easy-commands pull request #1
Opened 2020-04-24 16:08 UTC by Eveldee

This allows one and only one subcommand to be marked as **default** in a command.
When a subcommand is marked as **default** (see DefaultExampleCommands.cs), it has the following effects:
- If no subcommand is specified it will fallback to the **default** one without any args
- If an unknown subcommand is specified, it will fallback to the **default** one with everything after the parent command as args

Tell me if you want to change how the **default** subcommand is set, I first tried with a "DefaultSubCommand" Attribute, but it felt wrong so I did it with another constructor for the SubCommand Attribute.

I also fixed a little issue with tests as my CultureInfo use ',' instead of '.' for the decimal separator, now it works with both, using the CurrentCulture one.

2020-04-25 01:26 UTC, ZakFahey requested changes

2020-04-25 01:26 UTC, ZakFahey commented on EasyCommands/EasyCommands/Commands/CommandGroupDelegate.cs
> +                            throw new CommandRegistrationException($"There is two or more default sub commands in {command.Name}.");
Grammar: should be "there are two"

2020-04-25 01:26 UTC, ZakFahey commented on EasyCommands/EasyCommands/Attributes.cs
> +        }
Can you add an override with zero arguments that acts as the default subcommand and has no names? You may also want to double check that it doesn't clash with a zero-length params array.

2020-04-25 01:26 UTC, ZakFahey commented on EasyCommands/EasyCommands/Commands/CommandGroupDelegate.cs
>          public string SubcommandList()
Can you make sure that any user messages (error messages, the HelpCommand in the Example project) generated by this system show reasonable looking messages for default subcommands? I believe you'd have to change syntaxDocumentation in BaseCommandDelegate.

2020-04-25 02:36 UTC, ZakFahey commented
I'm also not sure if there's any point to there being a named failover for default commands. It should just be what happens when you have no name argument in the attribute. Nobody's going to type a more verbose alt alias of a command.

2020-04-25 02:37 UTC, ZakFahey commented
Also, could you document this functionality in the documentation?

2020-04-25 09:00 UTC, Eveldee commented
I tried naming a command with an empty stirng: "" and it worked well with documentation using EasyCommandsTShock on a Terraria server so I guess if I do that, it will be good.
I'm going to try doing this

2020-04-25 09:18 UTC, Eveldee commented
I just realized when doing the tests that the empty constructor is used for inferring the command name from the method name, should I create a constructor with only one bool argument instead for the default one? So if it's true, it will se the name to "" and if it's false, it will just do the same as no argument.

2020-04-25 16:31 UTC, ZakFahey commented
I think you can go without the boolean argument altogether and just say that if there is no name, it's a default command. If method overriding doesn't work because C# interprets it as a zero-length params array, you can just check if length is zero there instead of having another constructor.

2020-04-25 16:36 UTC, ZakFahey commented
An attribute with one isDefault should be okay, but it might encourage people to do `[SubCommand(true)]` instead of `[SubCommand(isDefault: true)]`. Both compile but one is less readable. I'd maybe consider a format that forces you to be explicit in how it shows, such as with an enum argument or another `DefaultSubCommand` attribute class.

With a subcommand of "" I think that it might look okay at first glance but it would have an extra space. You'd see `/command<two spaces>arg arg` (GitHub formats it away so I can't show it...)

2020-04-25 16:50 UTC, Eveldee commented
I have to give a name to the command so "" seems good for me, and I need a way to recognize between an empty constructor which should infer the command name from method name or for a default subcommand.
Using an enum is a good idea if you want it to be clear, I'm going to try it

2020-04-25 17:00 UTC, Eveldee commented
I have this so far:
```cs
/// <summary>
/// Change how a <see cref="SubCommand"/> is executed
/// </summary>
public enum SubCommandType
{
	/// <summary>
	/// This does nothing special, it just execute the command when it's called
	/// </summary>
	Standard,
	/// <summary>
	/// Mark the command as the default one, it will be executed whenever an invalid command is executed
	/// </summary>
	Default
}
```
```cs
/// <param name="subCommandType">Determine whether this subcommand is a default subcommand or not</param>
public SubCommand(SubCommandType subCommandType) : base(subCommandType == SubCommandType.Default ? new string[] { "" } : Array.Empty<string>())
{
	IsDefault = subCommandType == SubCommandType.Default;
}
```

2020-04-25 17:08 UTC, Eveldee commented
How should the help display the command ?
Currently, it's:
```
default <hello|bye|>
```

It may be better like this:
```
default [<hello|bye>]
```
Or like this:
```
default [hello|bye]
```

2020-04-25 19:49 UTC, ZakFahey commented
Something like `default <hello|bye>`. Omit the default from the subcommand list.

2020-04-26 11:40 UTC, Eveldee commented
I've made all the changes you requested, I tried it in real conditions and it worked well.
I also made some little changes to the documentation to make it more readable.

I now need to investigate on the other repository why the `[AllowServer]` attribute does not work with TShock, I'll open a PR as I did for this one if I find the answer.

2020-04-26 11:55 UTC, Eveldee commented
Here is a little example using it on my Terraria server with the following command:
```cs
[Command("vote", "v")]
[HelpText("Vote for different things.")]
public class VoteCommand : CommandCallbacks<TSPlayer>
{
	[SubCommand("time", "t")]
	[HelpText("Vote for a time set.")]
	public void Time([AllowSpaces] string time)
	{
		// Some code
	}

	[SubCommand("rain", "r")]
	[HelpText("Vote for a rain on/off toggle")]
	public void Rain()
	{
		// Some code
	}

	[SubCommand(SubCommandType.Default)]
	[HelpText("Vote for the last request.")]
	[AllowServer(false)]
	public void Vote()
	{
		// Some code
	}
}
```

Result:
```
help vote
Server executed: /help vote.
/vote help:
Vote for different things. Syntax: /vote <time|rain>
: vote abc
Server executed: /vote abc.
Incorrect number of arguments! Proper syntax: /vote
: vote time
Server executed: /vote time.
Incorrect number of arguments! Proper syntax: /vote time <time>
: vote time 12:45
Server executed: /vote time 12:45.
A vote has started for: "Setting time to 12:45", type "/vote" to vote
Vote status: 0/1
: vote
Server executed: /vote.
Server voted, vote status: 1/1
Vote has succeeded, executing request...
Time set to 12:45
```

Also note that the server can still vote even if there is `[AllowServer(false)]`, btu that's an issue for the other repository.

2020-04-27 00:53 UTC, ZakFahey commented
Ok, I'll need to make a Nuget release and then have a PR to reference the newer version in the TShock library.

2020-04-27 00:53 UTC, merged